# This is a TOML configuration file.

# Connection details of ethereum blockchain.
[ethereum]
URL = ""
URLRPC = ""

  [ethereum.account]
  KeyFile = ""

  # Addresses of contracts deployed on ethereum blockchain.
  [ethereum.ContractAddresses]
  BondedECDSAKeepFactory = ""
  TBTCSystem = ""

[LibP2P]
Peers = []
Port = ""
AnnouncedAddresses = []

[Storage]
DataDir = ""
