---
apiVersion: v1
kind: Service
metadata:
  name: keep-ecdsa-6
  namespace: default
  labels:
    app: keep
    type: ecdsa
    id: "6"
    network: ropsten
    chain: ethereum
spec:
  type: LoadBalancer
  ports:
    - port: 3919
      targetPort: 3919
      name: tcp-3919
    - port: 9601
      targetPort: 9601
      name: tcp-9601
  selector:
    app: keep
    type: ecdsa
    id: "6"
    network: ropsten
    chain: ethereum
