name: Go / Celo

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-celo-cache
          key: ${{ runner.os }}-buildx-celo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-celo-

      # TODO: This step was left here intentionally so we can track disk space
      # usage for a while. We were trying to fight problems with out of disk space
      # that happened due to the size of data restored from cache. The cache size
      # was growing linearly with subsequent workflow runs. We want to observe
      # available disk space for `/`. Fresh execution starts with 21 GB, we expect
      # to have no less than 15 GB after the cache is restored.
      - run: sudo df -h

      - name: Build Docker Build Image
        uses: docker/build-push-action@v2
        with:
          target: gobuild
          tags: go-build-env-celo
          build-args: |
            HOST_CHAIN=celo
          load: true # load image to local registry to use it in next steps
          cache-from: type=local,src=/tmp/.buildx-celo-cache
          cache-to: type=local,dest=/tmp/.buildx-celo-cache

      - name: Run Go tests
        run: |
          docker run \
            --workdir /go/src/github.com/keep-network/keep-ecdsa \
            go-build-env-celo \
            gotestsum -- -tags=celo,musl ./...

      - name: Login to Google Container Registry
        if:  |
          startsWith(github.ref, 'refs/heads/releases/alfajores')
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GCR_REGISTRY_URL }}
          username: _json_key
          password: ${{ secrets.KEEP_TEST_GCR_JSON_KEY }}

      - name: Build and publish Docker Runtime Image
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: 'keep-ecdsa-celo'
          GOOGLE_PROJECT_ID: ${{ secrets.KEEP_TEST_GOOGLE_PROJECT_ID }}
        with:
          # GCR image should be named according to following convention:
          # HOSTNAME/PROJECT-ID/IMAGE:TAG
          # We don't use TAG yet, will be added at later stages of work on RFC-18.
          tags: ${{ secrets.GCR_REGISTRY_URL }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}
          labels: revision=${{ github.sha }}
          build-args: |
            HOST_CHAIN=celo
            REVISION=${{ github.sha }}
          # VERSION= ? TODO: Configure version, sample: 1.7.6
          push: |
            ${{ startsWith(github.ref, 'refs/heads/releases/alfajores') }}