name: Code Formatting

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Install prettier and plugins
        run: npm install prettier prettier-plugin-sh prettier-plugin-toml

      - name: Check formatting
        run: npx prettier --check .
