name: NPM

on:
  push:
    branches:
      - master
      - "rfc-18/**" # TODO: Remove after testing
    paths:
      - "solidity/contracts/**"
      - "solidity/package.json"
      - "solidity/package-lock.json"
      - '.github/workflows/npm.yml' # TODO: Remove after testing

jobs:
  npm-compile-publish-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-solidity-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install dependencies
        run: npm ci

      - name: Resolve latest contracts
        working-directory: ./solidity
        run: |
          npm update \
            @keep-network/keep-core \
            @keep-network/sortition-pools

      - name: Compile contracts
        run: npx truffle compile

      - name: Copy artifacts
        run: |
          mkdir -p artifacts
          cp -r build/contracts/* artifacts/

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          work-dir: ./solidity
          environment: dev
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --dry-run # TODO: Remove --dry-run after testing
