name: NPM

on:
  push:
    branches:
      - master
    paths:
      - "solidity/contracts/**"
      - "solidity/package.json"
      - "solidity/package-lock.json"

jobs:
  publish-contracts:
    # Don't run the job if commit message starts with `[CI]`.
    if: startsWith(github.event.commits[0].message, '[CI]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "11.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Publish package
        working-directory: ./solidity
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version
        working-directory: ./solidity
        run: |
          PACKAGE_VERSION=$(npm version prerelease --preid=pre)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
      - name: Setup git
        run: |
          git remote set-url origin https://${{ secrets.CI_GITHUB_TOKEN }}@github.com/keep-network/keep-ecdsa.git
          git config user.email "thesis-heimdall@users.noreply.github.com"
          git config user.name "Heimdall"
      - name: Commit
        working-directory: ./solidity
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          GITHUB_REF=${{ github.ref }}
          BRANCH=${GITHUB_REF#refs/heads/} # strip branch name from github reference, branch name is prefixed with `refs/heads`
          git checkout $BRANCH
          git add package.json package-lock.json
          git commit -m "[CI] Auto-bump pre-release package to $PACKAGE_VERSION"
          git push origin $BRANCH
